### ISSUE TITLE
The first time need more than 20 mins for init

### ISSUE THREAD

**Issue by zengxc-1996** [Websoft9/ansible-superset#7]
When completed deployment, the first time  access Superset need more than 20 mins for init.  
Then, restart system, I can access it very quickly.

**Comment by chendelin1982** [comment]
The reason is that node container need install node package and build node, this action need much time
```
  superset-node:
    image: node:14
    container_name: superset_node
    command: ["/app/docker/docker-frontend.sh"]
    env_file: docker/.env
    depends_on: *superset-depends-on
    volumes: *superset-volumes
```
